# @Author: NoRain 
# @Date: 2022-11-13 19:16:10 
# @Last Modified by:   NoRain 
# @Last Modified time: 2022-11-13 19:16:10

#标签页
favicon: img/favicon.ico

# 版权开始时间
since: 2022


#关于
about:
  head: https://avatars.githubusercontent.com/u/66503849?v=4
  name: 无雨
  description: "你好，我是无雨。一名普普通通的游戏玩家。希望自己不会丧失对生活的热情。"

